# Generated by Django 5.1.3 on 2024-11-23 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0003_alter_category_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Назва вікторини"
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(1, "Легкий"), (2, "Середній"), (3, "Важкий")],
                        verbose_name="Рівень складності",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вікторина",
                "verbose_name_plural": "Вікторини",
                "ordering": ["category", "name"],
            },
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["quiz", "id"],
                "verbose_name": "Питання",
                "verbose_name_plural": "Питання",
            },
        ),
        migrations.AlterModelOptions(
            name="quizcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Категорія вікторини",
                "verbose_name_plural": "Категорії вікторин",
            },
        ),
        migrations.RemoveField(
            model_name="question",
            name="category",
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(max_length=255, verbose_name="Правильна відповідь"),
        ),
        migrations.AlterField(
            model_name="question",
            name="options",
            field=models.JSONField(
                help_text="Список варіантів відповідей у форматі JSON",
                verbose_name="Варіанти відповідей",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(unique=True, verbose_name="Текст питання"),
        ),
        migrations.AlterField(
            model_name="quizcategory",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Назва категорії"
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="quizzes.quizcategory",
                verbose_name="Категорія",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quizzes.quiz",
                verbose_name="Вікторина",
            ),
            preserve_default=False,
        ),
    ]
